/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Kalam', 'cursive', 'sans-serif'],
        hand: ['"Patrick Hand"', 'cursive', 'sans-serif'],
        sans: ['"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        cream: '#fdfbf7',
        studio: {
          bg: 'var(--bg-primary)',
          surface: 'var(--bg-surface)',
          panel: 'var(--bg-surface)',
          elevated: 'var(--bg-elevated)',
          hover: 'var(--bg-hover)',
          muted: 'var(--bg-muted)',
          mutedText: 'var(--text-muted)',
          postit: 'var(--bg-postit)',
          border: 'var(--border-color)',
          borderLight: 'var(--border-subtle)',
          borderSubtle: 'var(--border-subtle)',
          text: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          dim: 'var(--text-dim)',
          red: 'var(--accent-red)',
          redText: 'var(--accent-red-text)',
          blue: 'var(--accent-blue)',
          yellow: 'var(--accent-yellow)',
          green: 'var(--accent-green)',
          purple: 'var(--accent-purple)',
          cyan: 'var(--accent-blue)',
          indigo: 'var(--accent-purple)',
          amber: 'var(--accent-yellow)',
          emerald: 'var(--accent-green)',
          rose: 'var(--accent-red)',
        },
        pop: {
          bg: 'var(--bg-primary)',
          fg: 'var(--text-primary)',
          muted: 'var(--bg-muted)',
          mutedFg: 'var(--text-muted)',
          violet: 'var(--accent-purple)',
          pink: 'var(--accent-red)',
          yellow: 'var(--accent-yellow)',
          mint: 'var(--accent-green)',
          cyan: 'var(--accent-blue)',
          coral: 'var(--accent-red)',
          border: 'var(--border-color)',
          borderLight: 'var(--border-subtle)',
          card: 'var(--bg-surface)',
        }
      },
      boxShadow: {
        'sketch-xs': 'var(--shadow-paper-xs)',
        'sketch': 'var(--shadow-paper)',
        'sketch-md': 'var(--shadow-paper-md)',
        'sketch-lg': 'var(--shadow-paper-lg)',
        'sketch-red': 'var(--shadow-paper-red)',
        'sketch-blue': 'var(--shadow-paper-blue)',
        'sketch-yellow': 'var(--shadow-paper-yellow)',
        'pop-xs': 'var(--shadow-paper-xs)',
        'pop-sm': 'var(--shadow-paper-sm)',
        'pop': 'var(--shadow-paper)',
        'pop-md': 'var(--shadow-paper-md)',
        'pop-lg': 'var(--shadow-paper-lg)',
        'pop-xl': 'var(--shadow-paper-lg)',
        'pop-2xl': 'var(--shadow-paper-lg)',
        'pop-violet': 'var(--shadow-paper-blue)',
        'pop-pink': 'var(--shadow-paper-red)',
        'pop-yellow': 'var(--shadow-paper-yellow)',
        'pop-mint': 'var(--shadow-paper)',
        'pop-cyan': 'var(--shadow-paper-blue)',
        'cinema': 'var(--shadow-paper)',
      },
      borderRadius: {
        'wobbly': '255px 15px 225px 15px / 15px 225px 15px 255px',
        'wobbly-md': '255px 25px 225px 25px / 25px 225px 25px 255px',
        'wobbly-lg': '30px 180px 25px 190px / 190px 25px 180px 30px',
        'wobbly-sm': '120px 10px 110px 10px / 10px 110px 10px 120px',
        'wobbly-pill': '255px 25px 225px 25px / 25px 225px 25px 255px',
        'blob': '24px 24px 24px 0px',
        'speech': '20px 20px 20px 0px',
      },
      backgroundImage: {
        'dot-grid': 'radial-gradient(var(--grid-dot-color) 1.5px, transparent 1.5px)',
        'stripes-diagonal': 'repeating-linear-gradient(45deg, var(--bg-muted), var(--bg-muted) 10px, var(--bg-surface) 10px, var(--bg-surface) 20px)',
      },
      transitionTimingFunction: {
        'bounce-spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'wiggle': 'wiggle 1.2s ease-in-out infinite',
        'pop-in': 'popIn 0.25s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'float-slow': 'floatPlayful 4s ease-in-out infinite',
      },
      keyframes: {
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(2deg)' },
          '75%': { transform: 'rotate(-2deg)' },
        },
        popIn: {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(6px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        floatPlayful: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-4px) rotate(1deg)' },
        },
      },
    },
  },
  plugins: [],
}
